interfaces: 
  - wlan0
networks:
    192.168.5.0/24:
        probation_period: 86400
        server_id: 192.168.5.1
        ranges:
            - start: 192.168.5.2
              end: 192.168.5.250
              config:
                  lease_time:
                      default: 3600
                      min: 1200
                      max: 4800
              options:
                  values:
                      1: # subnet mask (if not specified, comes from `interfaces`)
                          type: ip
                          value: 255.255.255.0
                      3: # router (if not specified, will come from `interfaces`)
                          type: ip_list
                          value:
                              - 192.168.5.1
                      6: # domain name (if running a DNS server like dnsmasq also, use its IP)
                          type: ip_list
                          value:
                              - 8.8.8.8
                      28: # broadcast addr (if not specified, comes from `interfaces`)
                         type: ip
                         value: 192.168.5.255
